export type DispatchStatus = 'READY_FOR_OPERATIONS' | 'PREPARING' | 'ASSIGNED' | 'SCHEDULED' | 'READY_FOR_ROUTE' | 'IN_ROUTE' | 'DELIVERED' | 'INCIDENT' | 'REPROGRAMMED' | 'CANCELLED';
export interface ApiPage<T> { items: readonly T[]; page: number; size: number; total: number; }
export interface DispatchAssignment { responsibleMembershipId: string | null; responsibleDisplayName: string | null; vehicleReference: string | null; routeName: string | null; }
export interface DispatchOrder { id: string; dispatchNumber: string; reservationId: string | null; salesOrderId: string | null; salesOrderNumber: string; clientAccountId: string | null; status: DispatchStatus | string; destination: string | null; deliveryWindowStart: string | null; deliveryWindowEnd: string | null; eta: string | null; assignment: DispatchAssignment | null; temperatureMin: number | null; temperatureMax: number | null; temperatureUnit: string | null; temperatureStatus: string; podId: string | null; podStatus: string | null; version: number; updatedAt: string; alerts: readonly string[]; }
export interface DispatchEvent { id: string; type: string; fromStatus: string | null; toStatus: string | null; occurredAt: string; buyerVisible: boolean; summary: string | null; }
export interface HandoffNote { id: string; dispatchOrderId: string; note: string; authorMembershipId: string; occurredAt: string; dispatchVersion: number; }
export interface OperationsDashboard { readyForOperations: number; preparing: number; assigned: number; scheduled: number; readyForRoute: number; inRoute: number; incidents: number; deliveredToday: number; temperatureAlerts: number; podPending: number; reservationsReady: number; }
export interface OperationalAnalytics { from: string; to: string; dispatches: number; delivered: number; incidents: number; temperatureExcursions: number; podCompleted: number; onTimeRate: number; averagePreparationMinutes: number; averageRouteMinutes: number; }
export interface ProofOfDelivery { podId: string | null; dispatchOrderId: string; dispatchNumber: string; status: string; receiverName: string | null; completedAt: string | null; notes: string | null; photoEvidenceDeclared: boolean; signatureEvidenceDeclared: boolean; updatedAt: string; }
