import { Injectable, inject } from '@angular/core';
import { LanguageService } from '../../../core/i18n/language.service';

type MessageValues = Readonly<Record<string, string | number>>;

const EN: Record<string, string> = {
  pageEyebrow: 'Tenant management', pageTitle: 'Company administration', pageSubtitle: 'Organization identity, workspaces, internal access and operational policy.',
  loading: 'Loading', loadingAdministration: 'Loading company administration', loadErrorTitle: 'Unable to load administration', loadErrorDescription: 'The tenant scope could not be loaded. Retry when the API is available.', retry: 'Retry', reload: 'Reload',
  readOnly: 'Company Owner view: administrative mutations are disabled.', technicalReadOnly: 'Technical tenant configuration is managed by a Tenant Administrator.', saved: 'Saved', workspaceCreated: 'Workspace created.', workspaceSettingsLoaded: 'Workspace settings loaded.', staleVersion: 'This record changed elsewhere. The latest data was reloaded; review it before saving again.', staleReloaded: 'Latest tenant data reloaded.',
  overview: 'Overview', sectionsLabel: 'Company administration sections', organizationTab: 'Organization & workspaces', teamTab: 'Team & invitations', settingsTab: 'Settings', accessTab: 'Access & plan',
  organization: 'Organization', workspaces: 'Workspaces', members: 'Internal members', currentPlan: 'Current plan', configuredTenantWorkspaces: 'Configured tenant workspaces.', fixedRoleMemberships: 'Fixed-role memberships in this tenant.', referenceUsage: 'Reference usage; no billing or upgrade action.', manageWorkspaces: 'Manage workspaces', manageTeam: 'Manage team', viewAccessUsage: 'View access and usage',
  identityProfile: 'Identity and legal profile', legalName: 'Legal name', displayName: 'Display name', businessIdentifier: 'Business identifier', operationCategory: 'Operation category', saveOrganization: 'Save organization', required: 'Required', organizationProfileEmpty: 'Organization profile is empty.',
  configured: '{count} configured', noWorkspaces: 'No workspaces are available.', newWorkspaceName: 'New workspace name', slug: 'Slug', createWorkspace: 'Create workspace', configure: 'Configure', edit: 'Edit', save: 'Save', cancel: 'Cancel', editWorkspace: 'Edit workspace', suspend: 'Suspend', reactivate: 'Reactivate', workspaceSettings: 'Workspace settings', workspaceSettingsSubtitle: 'Default behavior for the selected workspace', defaultWorkspaceBehavior: 'Default workspace behavior', warehousePreferenceStrategy: 'Warehouse preference strategy', warehousePreferenceAuthority: 'Warehouse strategy is managed in Operational rules', saveWorkspaceSettings: 'Save workspace settings', workspaceRequired: 'Select a workspace to edit workspace settings.',
  teamMembers: 'Team members', memberships: '{count} memberships', noMemberships: 'No internal memberships are configured.', fixedRoles: 'Assignable team roles', roleGovernanceHint: 'Company Owner is the unique business owner. Tenant Admin manages technical tenant configuration; neither role is offered as an additional invitation role.', details: 'Details', close: 'Close', memberDetail: 'Member detail', userId: 'User ID', membershipId: 'Membership ID', status: 'Status', roleConfirmation: 'Confirm role change', membershipLifecycleConfirmation: 'Confirm membership status change', workspaceLifecycleConfirmation: 'Confirm workspace status change', currentRoles: 'Current roles', nextRoles: 'New roles', confirm: 'Confirm change', roleChangeCancelled: 'Role change cancelled', finalAdminHint: 'Removing the final active Tenant Admin is rejected by the API.',
  invitations: 'Invitations', internalAccessOnly: 'Internal access only', inviteInternalMember: 'Invite internal member', email: 'Email', sendInvitation: 'Send invitation', noInvitations: 'No invitations have been created.', expires: 'Expires', resend: 'Resend', revoke: 'Revoke', pending: 'Pending', invitationCreated: 'Invitation created',
  regionalSettings: 'Regional settings', localeAndTimezone: 'Locale and timezone', timezone: 'Timezone', language: 'Language', english: 'English', spanish: 'Spanish', currency: 'Currency', countryRegion: 'Country or region', dateTimePolicy: 'Date and time policy', locale: 'Locale', saveRegional: 'Save regional settings',
  units: 'Units', coldChainMeasurement: 'Cold-chain measurement preferences', mass: 'Mass', temperature: 'Temperature', distance: 'Distance', volume: 'Volume', kilograms: 'Kilograms', pounds: 'Pounds', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometres: 'Kilometres', miles: 'Miles', cubicMetres: 'Cubic metres', pallets: 'Pallets', cubicFeet: 'Cubic feet', saveUnits: 'Save units',
  operationalRules: 'Operational rules', fulfillmentDefaults: 'Workspace fulfillment defaults', warehouseSelection: 'Warehouse selection', orderCutoff: 'Order cutoff', fulfillmentDefault: 'Fulfillment default', inventoryVisibility: 'Inventory visibility', buyerAvailability: 'Buyer availability', manual: 'Manual', preferred: 'Preferred', workspaceHours: 'Workspace hours', fixedTime: 'Fixed time', standard: 'Standard', fefo: 'FEFO', summary: 'Summary', detailed: 'Detailed', availableOnly: 'Available only', allActive: 'All active', openingTime: 'Opening time', closingTime: 'Closing time', orderCutoffMinutes: 'Order cutoff minutes', requireThermalLog: 'Require thermal log', saveOperational: 'Save operational rules', selectedWorkspace: 'Workspace: {workspace}',
  notifications: 'Notifications', inAppEmailPreferences: 'In-app and email preferences', noNotificationPreferences: 'No notification preferences are configured.', enabled: 'Enabled', disabled: 'Disabled',
  securitySettings: 'Security settings', safeTenantPolicy: 'Safe tenant policy bounds', minimumPasswordLength: 'Minimum password length', sessionDuration: 'Session duration (minutes)', invitationExpiration: 'Invitation expiration (hours)', allowedEmailDomain: 'Allowed email domain', saveSecurity: 'Save security settings',
  customFields: 'Custom fields', typedDefinitions: 'Typed administrative definitions', key: 'Key', type: 'Type', scope: 'Scope', displayOrder: 'Display order', unique: 'Unique', createDefinition: 'Create definition', editDefinition: 'Edit definition', saveDefinition: 'Save definition', noCustomFields: 'No custom-field definitions are configured.', text: 'Text', number: 'Number', decimal: 'Decimal', boolean: 'Boolean', date: 'Date', product: 'Product', clientAccount: 'Client account', dispatch: 'Dispatch', order: 'Order', activate: 'Activate', deactivate: 'Disable',
  accessMatrix: 'Access matrix', fixedRolePermissions: 'Fixed role permissions', permissions: '{count} permissions', accessMatrixEmpty: 'Access matrix is empty.', planUsage: 'Plan and usage', referenceOnly: 'Reference-only view', currentReferencePlan: 'Current reference plan', activeUsers: 'Active users', activeWorkspaces: 'Active workspaces', transactions: 'Transactions', referenceCurrent: 'Current reference', referenceMetadata: 'Reference metadata only', planUnavailable: 'Plan usage is not available.',
  roleTenantAdmin: 'Tenant administration', roleCompanyOwner: 'Company owner', roleSales: 'Sales', roleWarehouse: 'Warehouse', roleLogistics: 'Logistics',
  active: 'Active', suspended: 'Suspended', disabledStatus: 'Disabled', invited: 'Invited', revoked: 'Revoked', accepted: 'Accepted',
  invitationAcceptance: 'Accept invitation', invitationAcceptanceDescription: 'Use the secure invitation link to activate internal access.', invitationToken: 'Invitation token', newUser: 'New Nexa user', existingUser: 'Existing Nexa user', newUserDescription: 'Create the account attached to this invitation.', existingUserDescription: 'The invited email is matched to an existing active account by the API.', existingUserContractHint: 'The current acceptance contract still requires a valid password field; no separate account preflight is available.', acceptInvitation: 'Accept invitation', invitationAccepted: 'Invitation accepted. You can now sign in to Platform.', invitationAcceptedRoles: 'Assigned roles: {roles}', backToSignIn: 'Go to sign in', password: 'Password', confirmPassword: 'Confirm password', passwordMismatch: 'Passwords do not match.', tokenRequired: 'Invitation token is required.', passwordPolicy: 'Use 12 to 128 characters.', displayNameRequired: 'Display name is required for a new user.',
  errorInvitationInvalid: 'The invitation is invalid or expired.', errorInvitationConflict: 'The invitation could not be accepted in its current state.', errorConcurrency: 'The record changed elsewhere. The latest data was reloaded.', errorPrecondition: 'The server requires a current record version.', errorLastActiveOwner: 'At least one active Company Owner must remain. Choose another owner before removing this role.', errorDefault: 'The operation could not be completed. Try again.'
};

const ES: Record<string, string> = {
  pageEyebrow: 'Administración del tenant', pageTitle: 'Administración de compañía', pageSubtitle: 'Identidad de la organización, workspaces, acceso interno y políticas operativas.',
  loading: 'Cargando', loadingAdministration: 'Cargando administración de compañía', loadErrorTitle: 'No se pudo cargar la administración', loadErrorDescription: 'No se pudo cargar el alcance del tenant. Reintenta cuando la API esté disponible.', retry: 'Reintentar', reload: 'Recargar',
  readOnly: 'Vista de Company Owner: las mutaciones administrativas están deshabilitadas.', technicalReadOnly: 'La configuración técnica del tenant la gestiona un Tenant Administrator.', saved: 'Guardado', workspaceCreated: 'Workspace creado.', workspaceSettingsLoaded: 'Configuración del workspace cargada.', staleVersion: 'Este registro cambió en otro lugar. Se cargaron los datos más recientes; revísalos antes de guardar.', staleReloaded: 'Se cargaron los datos más recientes del tenant.',
  overview: 'Resumen', sectionsLabel: 'Secciones de administración de compañía', organizationTab: 'Organización y workspaces', teamTab: 'Equipo e invitaciones', settingsTab: 'Configuración', accessTab: 'Acceso y plan',
  organization: 'Organización', workspaces: 'Workspaces', members: 'Miembros internos', currentPlan: 'Plan actual', configuredTenantWorkspaces: 'Workspaces configurados del tenant.', fixedRoleMemberships: 'Memberships con roles fijos de este tenant.', referenceUsage: 'Uso referencial; no incluye facturación ni upgrade.', manageWorkspaces: 'Gestionar workspaces', manageTeam: 'Gestionar equipo', viewAccessUsage: 'Ver acceso y uso',
  identityProfile: 'Identidad y perfil legal', legalName: 'Razón social', displayName: 'Nombre visible', businessIdentifier: 'Identificador empresarial', operationCategory: 'Categoría de operación', saveOrganization: 'Guardar organización', required: 'Obligatorio', organizationProfileEmpty: 'El perfil de organización está vacío.',
  configured: '{count} configurados', noWorkspaces: 'No hay workspaces disponibles.', newWorkspaceName: 'Nombre del nuevo workspace', slug: 'Slug', createWorkspace: 'Crear workspace', configure: 'Configurar', edit: 'Editar', save: 'Guardar', cancel: 'Cancelar', editWorkspace: 'Editar workspace', suspend: 'Suspender', reactivate: 'Reactivar', workspaceSettings: 'Configuración del workspace', workspaceSettingsSubtitle: 'Comportamiento predeterminado del workspace seleccionado', defaultWorkspaceBehavior: 'Comportamiento predeterminado', warehousePreferenceStrategy: 'Estrategia de preferencia de almacén', warehousePreferenceAuthority: 'La estrategia de almacén se gestiona en Reglas operativas', saveWorkspaceSettings: 'Guardar configuración del workspace', workspaceRequired: 'Selecciona un workspace para editar su configuración.',
  teamMembers: 'Miembros del equipo', memberships: '{count} memberships', noMemberships: 'No hay memberships internas configuradas.', fixedRoles: 'Roles asignables del equipo', roleGovernanceHint: 'Company Owner es el único dueño empresarial. Tenant Admin gestiona la configuración técnica del tenant; ninguno se ofrece como rol adicional en invitaciones.', details: 'Detalle', close: 'Cerrar', memberDetail: 'Detalle del miembro', userId: 'ID de usuario', membershipId: 'ID de membership', status: 'Estado', roleConfirmation: 'Confirmar cambio de roles', membershipLifecycleConfirmation: 'Confirmar cambio de estado de membership', workspaceLifecycleConfirmation: 'Confirmar cambio de estado del workspace', currentRoles: 'Roles actuales', nextRoles: 'Nuevos roles', confirm: 'Confirmar cambio', roleChangeCancelled: 'Cambio de roles cancelado', finalAdminHint: 'La API rechaza eliminar el último Tenant Admin activo.',
  invitations: 'Invitaciones', internalAccessOnly: 'Solo acceso interno', inviteInternalMember: 'Invitar miembro interno', email: 'Correo', sendInvitation: 'Enviar invitación', noInvitations: 'No se han creado invitaciones.', expires: 'Vence', resend: 'Reenviar', revoke: 'Revocar', pending: 'Pendiente', invitationCreated: 'Invitación creada',
  regionalSettings: 'Configuración regional', localeAndTimezone: 'Locale y zona horaria', timezone: 'Zona horaria', language: 'Idioma', english: 'Inglés', spanish: 'Español', currency: 'Moneda', countryRegion: 'País o región', dateTimePolicy: 'Política de fecha y hora', locale: 'Locale', saveRegional: 'Guardar configuración regional',
  units: 'Unidades', coldChainMeasurement: 'Preferencias de medición de cadena de frío', mass: 'Masa', temperature: 'Temperatura', distance: 'Distancia', volume: 'Volumen', kilograms: 'Kilogramos', pounds: 'Libras', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometres: 'Kilómetros', miles: 'Millas', cubicMetres: 'Metros cúbicos', pallets: 'Pallets', cubicFeet: 'Pies cúbicos', saveUnits: 'Guardar unidades',
  operationalRules: 'Reglas operativas', fulfillmentDefaults: 'Predeterminados de fulfillment del workspace', warehouseSelection: 'Selección de almacén', orderCutoff: 'Corte de pedidos', fulfillmentDefault: 'Predeterminado de fulfillment', inventoryVisibility: 'Visibilidad de inventario', buyerAvailability: 'Disponibilidad para compradores', manual: 'Manual', preferred: 'Preferido', workspaceHours: 'Horario del workspace', fixedTime: 'Hora fija', standard: 'Estándar', fefo: 'FEFO', summary: 'Resumen', detailed: 'Detallada', availableOnly: 'Solo disponibles', allActive: 'Todos los activos', openingTime: 'Hora de apertura', closingTime: 'Hora de cierre', orderCutoffMinutes: 'Minutos de corte de pedido', requireThermalLog: 'Exigir registro térmico', saveOperational: 'Guardar reglas operativas', selectedWorkspace: 'Workspace: {workspace}',
  notifications: 'Notificaciones', inAppEmailPreferences: 'Preferencias dentro de la app y correo', noNotificationPreferences: 'No hay preferencias de notificación configuradas.', enabled: 'Activada', disabled: 'Desactivada',
  securitySettings: 'Configuración de seguridad', safeTenantPolicy: 'Límites seguros de política del tenant', minimumPasswordLength: 'Longitud mínima de contraseña', sessionDuration: 'Duración de sesión (minutos)', invitationExpiration: 'Expiración de invitación (horas)', allowedEmailDomain: 'Dominio de correo permitido', saveSecurity: 'Guardar seguridad',
  customFields: 'Campos personalizados', typedDefinitions: 'Definiciones administrativas tipadas', key: 'Clave', type: 'Tipo', scope: 'Alcance', displayOrder: 'Orden de visualización', unique: 'Único', createDefinition: 'Crear definición', editDefinition: 'Editar definición', saveDefinition: 'Guardar definición', noCustomFields: 'No hay definiciones de campos personalizadas.', text: 'Texto', number: 'Número', decimal: 'Decimal', boolean: 'Booleano', date: 'Fecha', product: 'Producto', clientAccount: 'Cuenta cliente', dispatch: 'Despacho', order: 'Pedido', activate: 'Activar', deactivate: 'Desactivar',
  accessMatrix: 'Matriz de acceso', fixedRolePermissions: 'Permisos de roles fijos', permissions: '{count} permisos', accessMatrixEmpty: 'La matriz de acceso está vacía.', planUsage: 'Plan y uso', referenceOnly: 'Vista solo referencial', currentReferencePlan: 'Plan referencial actual', activeUsers: 'Usuarios activos', activeWorkspaces: 'Workspaces activos', transactions: 'Transacciones', referenceCurrent: 'Referencia actual', referenceMetadata: 'Solo metadatos referenciales', planUnavailable: 'El uso del plan no está disponible.',
  roleTenantAdmin: 'Administración del tenant', roleCompanyOwner: 'Company Owner', roleSales: 'Ventas', roleWarehouse: 'Almacén', roleLogistics: 'Logística',
  active: 'Activo', suspended: 'Suspendido', disabledStatus: 'Deshabilitado', invited: 'Invitado', revoked: 'Revocada', accepted: 'Aceptada',
  invitationAcceptance: 'Aceptar invitación', invitationAcceptanceDescription: 'Usa el enlace seguro de invitación para activar el acceso interno.', invitationToken: 'Token de invitación', newUser: 'Usuario nuevo de Nexa', existingUser: 'Usuario existente de Nexa', newUserDescription: 'Crea la cuenta asociada a esta invitación.', existingUserDescription: 'La API vincula el correo invitado con una cuenta activa existente.', existingUserContractHint: 'El contrato actual de aceptación aún exige un campo de contraseña válido; no existe un preflight separado de cuenta.', acceptInvitation: 'Aceptar invitación', invitationAccepted: 'Invitación aceptada. Ya puedes ingresar a Platform.', invitationAcceptedRoles: 'Roles asignados: {roles}', backToSignIn: 'Ir a ingresar', password: 'Contraseña', confirmPassword: 'Confirmar contraseña', passwordMismatch: 'Las contraseñas no coinciden.', tokenRequired: 'El token de invitación es obligatorio.', passwordPolicy: 'Usa entre 12 y 128 caracteres.', displayNameRequired: 'El nombre visible es obligatorio para un usuario nuevo.',
  errorInvitationInvalid: 'La invitación no es válida o expiró.', errorInvitationConflict: 'La invitación no pudo aceptarse en su estado actual.', errorConcurrency: 'El registro cambió en otro lugar. Se cargaron los datos más recientes.', errorPrecondition: 'El servidor requiere una versión actual del registro.', errorLastActiveOwner: 'Debe permanecer al menos un Company Owner activo. Elige otro owner antes de retirar este rol.', errorDefault: 'No se pudo completar la operación. Inténtalo nuevamente.'
};

@Injectable({ providedIn: 'root' })
export class TenantAdministrationI18n {
  private readonly language = inject(LanguageService).currentLanguage;

  t(key: string, values: MessageValues = {}): string {
    const dictionary = this.language() === 'es' ? ES : EN;
    const template = dictionary[key] ?? EN[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
  }

  role(role: string): string {
    const key: Record<string, string> = { TENANT_ADMIN: 'roleTenantAdmin', COMPANY_OWNER: 'roleCompanyOwner', SALES: 'roleSales', WAREHOUSE: 'roleWarehouse', LOGISTICS: 'roleLogistics' };
    return this.t(key[role] ?? role);
  }

  status(status: string): string {
    const key: Record<string, string> = { ACTIVE: 'active', SUSPENDED: 'suspended', DISABLED: 'disabledStatus', INVITED: 'invited', PENDING: 'pending', REVOKED: 'revoked', ACCEPTED: 'accepted' };
    return this.t(key[status] ?? status);
  }

  notice(value: string): string {
    const normalized = value.toUpperCase().replaceAll(' ', '_').replaceAll('-', '_');
    const key: Record<string, string> = { WORKSPACE_CREATED: 'workspaceCreated', WORKSPACE_SETTINGS_LOADED: 'workspaceSettingsLoaded', INVITATION_CREATED: 'invitationCreated', STALE_RELOADED: 'staleReloaded' };
    return this.t(key[normalized] ?? (normalized.endsWith('_SAVED') ? 'saved' : normalized.toLowerCase().replaceAll('_', ' ')));
  }

  error(value: string | null): string {
    if (!value) return '';
    const key: Record<string, string> = { INVITATION_INVALID: 'errorInvitationInvalid', INVITATION_CONFLICT: 'errorInvitationConflict', CONCURRENCY_CONFLICT: 'errorConcurrency', LAST_ACTIVE_OWNER_REQUIRED: 'errorLastActiveOwner', STALE_VERSION: 'staleVersion', PRECONDITION_REQUIRED: 'errorPrecondition' };
    return this.t(key[value] ?? (value === 'REQUEST_FAILED' ? 'errorDefault' : value.replaceAll('_', ' ').toLowerCase()));
  }
}
