import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { DatePipe } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { PageHeaderComponent } from '../../shared/presentation/components/page-header/page-header.component';
import { SectionPanelComponent } from '../../shared/presentation/components/section-panel/section-panel.component';
import { WarehouseOperationsFacade } from '../application/warehouse-operations.facade';
import { Reservation } from '../domain/warehouse.models';

@Component({selector:'nexa-inventory-reservation-detail-page',standalone:true,imports:[DatePipe,ReactiveFormsModule,TranslatePipe,PageHeaderComponent,SectionPanelComponent],template:`<section class="page"><nexa-page-header [title]="'warehouse.reservationDetail'|translate" [subtitle]="'warehouse.loading'|translate" />@if(facade.loading()){<p>{{'warehouse.loading'|translate}}</p>}@else if(facade.error();as error){<p role="alert">{{error}}</p>}@else if(item();as reservation){<nexa-section-panel [title]="'warehouse.reservations'|translate"><p>{{'warehouse.fields.order'|translate}}: {{reservation.orderNumber}}</p><p>{{'warehouse.fields.status'|translate}}: {{('warehouse.status.'+reservation.status)|translate}}</p><p>{{'warehouse.fields.expires'|translate}}: {{reservation.expiresAt|date:'medium'}}</p><form [formGroup]="releaseForm" (ngSubmit)="release(reservation)"><input formControlName="reason" [placeholder]="'warehouse.fields.reason'|translate"><button type="submit" [disabled]="!facade.canWrite() || reservation.status !== 'RESERVED' || releaseForm.invalid">{{'warehouse.actions.release'|translate}}</button></form><ul>@for(allocation of reservation.allocations ?? [];track allocation.lotId){<li>{{allocation.quantity}} {{allocation.unit}} · {{allocation.expirationDate}}</li>}</ul></nexa-section-panel>}@else{<p>{{'warehouse.notFound'|translate}}</p>}</section>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class InventoryReservationDetailPageComponent {readonly facade=inject(WarehouseOperationsFacade);readonly id=inject(ActivatedRoute).snapshot.paramMap.get('reservationId')!;readonly item=this.facade.selectedReservation;private readonly fb=inject(FormBuilder);readonly releaseForm=this.fb.nonNullable.group({reason:['',Validators.required]});constructor(){this.facade.loadReservation(this.id);}release(reservation: Reservation):void{if(this.releaseForm.invalid)return;this.facade.release(reservation.id,reservation.version,this.releaseForm.controls.reason.value);}}
