import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { EmptyStateComponent } from '../../shared/presentation/components/empty-state/empty-state.component';
import { ErrorStateComponent } from '../../shared/presentation/components/error-state/error-state.component';
import { LoadingStateComponent } from '../../shared/presentation/components/loading-state/loading-state.component';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { PageHeaderComponent } from '../../shared/presentation/components/page-header/page-header.component';
import { SectionPanelComponent } from '../../shared/presentation/components/section-panel/section-panel.component';
import { WarehouseOperationsFacade } from '../application/warehouse-operations.facade';

@Component({selector:'nexa-inventory-reservations-page',standalone:true,imports:[DatePipe,RouterLink,PageHeaderComponent,SectionPanelComponent,LoadingStateComponent,ErrorStateComponent,EmptyStateComponent],template:`<section class="page"><nexa-page-header title="Inventory Reservations" subtitle="Reservation lifecycle and safe release" /> @if (facade.loading()){<nexa-loading-state label="Loading reservations" />} @else if (facade.error(); as error){<nexa-error-state title="Reservations unavailable" [description]="error" (retry)="facade.retry()" />} @else {<nexa-section-panel title="Reservations"> @if (facade.reservations().length){<div class="table-shell"><table><caption>Inventory reservations</caption><thead><tr><th scope="col">Order</th><th scope="col">Status</th><th scope="col">Expires</th><th scope="col">Actions</th></tr></thead><tbody>@for(item of facade.reservations();track item.id){<tr><td><a [routerLink]="['/ops/operations/inventory/reservations',item.id]">{{item.orderNumber}}</a></td><td>{{item.status}}</td><td>{{item.expiresAt|date:'short'}}</td><td><button type="button" (click)="facade.release(item.id,item.version,'Warehouse release')" [disabled]="!facade.canWrite() || item.status !== 'RESERVED'">Release</button></td></tr>}</tbody></table></div>} @else {<nexa-empty-state title="No reservations" description="There are no inventory reservations to display." />}</nexa-section-panel>}</section>`,styles:[`table{width:100%;border-collapse:collapse}th,td{padding:.65rem;text-align:left;border-bottom:1px solid var(--nexa-color-border-decorative)}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class InventoryReservationsPageComponent {readonly facade=inject(WarehouseOperationsFacade);constructor(){this.facade.load();}}
