import { Injectable, computed, inject, signal } from '@angular/core';
import { DispatchEvent, DispatchOrder, OperationalAnalytics, OperationsDashboard, ProofOfDelivery } from '../domain/logistics.models';
import { LogisticsApiService } from '../infrastructure/logistics-api.service';

@Injectable({ providedIn: 'root' })
export class LogisticsFacade {
  private readonly api=inject(LogisticsApiService); readonly loading=signal(false); readonly error=signal<string|null>(null); readonly dispatches=signal<readonly DispatchOrder[]>([]); readonly selected=signal<DispatchOrder|null>(null); readonly events=signal<readonly DispatchEvent[]>([]); readonly dashboard=signal<OperationsDashboard|null>(null); readonly analytics=signal<OperationalAnalytics|null>(null); readonly proof=signal<readonly ProofOfDelivery[]>([]); readonly metrics=computed(()=>this.dashboard());
  load():void{this.loading.set(true);this.error.set(null);this.api.dispatches().subscribe({next:value=>{this.dispatches.set(value.items);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar Dispatch Orders.');this.loading.set(false);}});}
  loadDashboard():void{this.loading.set(true);this.error.set(null);this.api.dashboard().subscribe({next:value=>{this.dashboard.set(value);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar el dashboard operativo.');this.loading.set(false);}});}
  loadDetail(id:string):void{this.loading.set(true);this.error.set(null);this.api.detail(id).subscribe({next:value=>{this.selected.set(value);this.api.events(id).subscribe({next:events=>this.events.set(events),error:()=>this.error.set('No se pudo cargar la línea de tiempo.')});this.loading.set(false);},error:()=>{this.error.set('Dispatch Order no disponible.');this.loading.set(false);}});}
  loadProof(status?:string):void{this.loading.set(true);this.api.proof(status).subscribe({next:value=>{this.proof.set(value.items);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar POD.');this.loading.set(false);}});}
  loadAnalytics(from:string,to:string):void{this.loading.set(true);this.api.analytics(from,to).subscribe({next:value=>{this.analytics.set(value);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar analytics.');this.loading.set(false);}});}
  command(action:(item:DispatchOrder)=>import('rxjs').Observable<DispatchOrder>,item:DispatchOrder):void{action(item).subscribe({next:value=>{this.selected.set(value);this.load();this.api.events(value.id).subscribe({next:events=>this.events.set(events)});},error:()=>this.error.set('La operación no pudo completarse; conserva el estado server-side.')} );}
  prepare(item:DispatchOrder):void{this.command(value=>this.api.prepare(value),item);} ready(item:DispatchOrder):void{this.command(value=>this.api.ready(value),item);} startRoute(item:DispatchOrder):void{this.command(value=>this.api.startRoute(value),item);}
  assign(item:DispatchOrder,payload:{responsibleMembershipId:string;vehicleReference?:string;routeName?:string}):void{this.command(value=>this.api.assign(value,payload),item);} schedule(item:DispatchOrder,payload:{deliveryWindowStart:string;deliveryWindowEnd:string;eta?:string}):void{this.command(value=>this.api.schedule(value,payload),item);} temperature(item:DispatchOrder,payload:{value:number;unit:string;source:string}):void{this.command(value=>this.api.temperature(value,payload),item);} incident(item:DispatchOrder,payload:{type:string;severity:string;buyerVisible:boolean;description:string}):void{this.command(value=>this.api.incident(value,payload),item);} reprogram(item:DispatchOrder,payload:{deliveryWindowStart:string;deliveryWindowEnd:string;eta?:string;reason:string}):void{this.command(value=>this.api.reprogram(value,payload),item);} complete(item:DispatchOrder,payload:{receiverName:string;completedAt:string;notes?:string;photoEvidenceDeclared:boolean;signatureEvidenceDeclared:boolean}):void{this.command(value=>this.api.complete(value,payload),item);}
  retry():void{this.load();}
}
