import { Injectable, computed, inject, signal } from '@angular/core';
import { forkJoin, switchMap } from 'rxjs';
import { AuthenticationService } from '../../iam/application/authentication.service';
import { DispatchEvent, DispatchOrder, DispatchStatus, OperationalAnalytics, OperationsDashboard, ProofOfDelivery } from '../domain/logistics.models';
import { LogisticsApiService } from '../infrastructure/logistics-api.service';

@Injectable({ providedIn: 'root' })
export class LogisticsFacade {
  private readonly api=inject(LogisticsApiService); private readonly authentication=inject(AuthenticationService); readonly canWrite=computed(()=>this.authentication.hasPermission('logistics:write')); readonly loading=signal(false); readonly error=signal<string|null>(null); readonly dispatches=signal<readonly DispatchOrder[]>([]); readonly selected=signal<DispatchOrder|null>(null); readonly events=signal<readonly DispatchEvent[]>([]); readonly dashboard=signal<OperationsDashboard|null>(null); readonly analytics=signal<OperationalAnalytics|null>(null); readonly proof=signal<readonly ProofOfDelivery[]>([]); readonly metrics=computed(()=>this.dashboard());
  load():void{this.loading.set(true);this.error.set(null);this.api.dispatches().subscribe({next:value=>{this.dispatches.set(value.items);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar Dispatch Orders.');this.loading.set(false);}});}
  loadDashboard():void{this.loading.set(true);this.error.set(null);this.api.dashboard().subscribe({next:value=>{this.dashboard.set(value);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar el dashboard operativo.');this.loading.set(false);}});}
  loadDetail(id:string):void{this.loading.set(true);this.error.set(null);this.api.detail(id).subscribe({next:value=>{this.selected.set(value);this.api.events(id).subscribe({next:events=>this.events.set(events),error:()=>this.error.set('No se pudo cargar la línea de tiempo.')});this.loading.set(false);},error:()=>{this.error.set('Dispatch Order no disponible.');this.loading.set(false);}});}
  readonly pendingProof=signal<readonly ProofOfDelivery[]>([]); readonly completedProof=signal<readonly ProofOfDelivery[]>([]);
  loadProof(status?:string):void{this.loading.set(true);this.error.set(null);if(status){this.api.proof(status).subscribe({next:value=>{this.proof.set(value.items);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar POD.');this.loading.set(false);}});return;}forkJoin({pending:this.api.proof('PENDING'),completed:this.api.proof('COMPLETED')}).subscribe({next:value=>{this.pendingProof.set(value.pending.items);this.completedProof.set(value.completed.items);this.proof.set([...value.pending.items,...value.completed.items]);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar POD.');this.loading.set(false);}});}
  loadAnalytics(from:string,to:string):void{this.loading.set(true);this.api.analytics(from,to).subscribe({next:value=>{this.analytics.set(value);this.loading.set(false);},error:()=>{this.error.set('No se pudo cargar analytics.');this.loading.set(false);}});}
  command(action:(item:DispatchOrder)=>import('rxjs').Observable<DispatchOrder>,item:DispatchOrder):void{if(!this.ensureWrite())return;action(item).subscribe({next:value=>{this.selected.set(value);this.load();this.api.events(value.id).subscribe({next:events=>this.events.set(events)});},error:()=>this.error.set('La operación no pudo completarse; conserva el estado server-side.')} );}
  completePending(item:ProofOfDelivery,payload:{receiverName:string;completedAt:string;notes?:string;photoEvidenceDeclared:boolean;signatureEvidenceDeclared:boolean}):void{if(!this.ensureWrite())return;this.loading.set(true);this.api.detail(item.dispatchOrderId).pipe(switchMap(dispatch=>this.api.complete(dispatch,payload))).subscribe({next:()=>this.loadProof(),error:()=>{this.error.set('No se pudo completar la entrega.');this.loading.set(false);}});}
  prepare(item:DispatchOrder):void{this.command(value=>this.api.prepare(value),item);} ready(item:DispatchOrder):void{this.command(value=>this.api.ready(value),item);} startRoute(item:DispatchOrder):void{this.command(value=>this.api.startRoute(value),item);}
  moveToStatus(item: DispatchOrder, target: DispatchStatus): void { if (target === item.status) return; if (target === 'PREPARING' && item.status === 'READY_FOR_OPERATIONS') { this.prepare(item); return; } if (target === 'READY_FOR_ROUTE' && item.status === 'SCHEDULED') { this.ready(item); return; } if (target === 'IN_ROUTE' && item.status === 'READY_FOR_ROUTE') { this.startRoute(item); return; } this.error.set('LOGISTICS_BOARD_DETAILS_REQUIRED'); }
  rollbackBoard(): void { this.load(); }
  create(reservationId:string,version:number):void{if(!this.ensureWrite())return;this.api.create(reservationId,version).subscribe({next:()=>this.load(),error:()=>this.error.set('No se pudo crear el despacho desde la reserva.')});}
  assign(item:DispatchOrder,payload:{responsibleMembershipId:string;vehicleReference?:string;routeName?:string}):void{this.command(value=>this.api.assign(value,payload),item);} schedule(item:DispatchOrder,payload:{deliveryWindowStart:string;deliveryWindowEnd:string;eta?:string}):void{this.command(value=>this.api.schedule(value,payload),item);} temperature(item:DispatchOrder,payload:{value:number;unit:string;source:string}):void{this.command(value=>this.api.temperature(value,payload),item);} incident(item:DispatchOrder,payload:{type:string;severity:string;buyerVisible:boolean;description:string}):void{this.command(value=>this.api.incident(value,payload),item);} reprogram(item:DispatchOrder,payload:{deliveryWindowStart:string;deliveryWindowEnd:string;eta?:string;reason:string}):void{this.command(value=>this.api.reprogram(value,payload),item);} complete(item:DispatchOrder,payload:{receiverName:string;completedAt:string;notes?:string;photoEvidenceDeclared:boolean;signatureEvidenceDeclared:boolean}):void{this.command(value=>this.api.complete(value,payload),item);}
  retry():void{this.load();}
  private ensureWrite(): boolean { if (this.canWrite()) return true; this.error.set('LOGISTICS_WRITE_FORBIDDEN'); return false; }
}
